CREATE TABLE IF NOT EXISTS chat_model_info (
  id bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  code varchar(50) NOT NULL COMMENT '模型编码',
  type varchar(10) NOT NULL COMMENT '模型类型TABLE,SQL',
  name varchar(100) DEFAULT NULL COMMENT '模型名称',
  content text NOT NULL COMMENT '模型内容，表或者sql',
  use_prompt text COMMENT '模型使用说明',
  business_prompt text COMMENT '模型业务限定提示词',
  yn tinyint NOT NULL DEFAULT '1' COMMENT '是否有效',
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS chat_model_schema (
  id bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  model_code varchar(200) NOT NULL COMMENT '模型编码',
  column_id varchar(1000) NOT NULL COMMENT '字段唯一ID',
  column_name varchar(200) NOT NULL COMMENT '字段中文名',
  column_comment varchar(1000) NOT NULL COMMENT '字段描述',
  few_shot text COMMENT '值枚举逗号分隔',
  data_type varchar(20) DEFAULT NULL COMMENT '字段值类型',
  synonyms varchar(300) DEFAULT NULL COMMENT '同义词',
  vector_uuid varchar(400) DEFAULT NULL COMMENT '向量库数据id',
  default_recall tinyint NOT NULL DEFAULT '0' COMMENT '默认召回',
  analyze_suggest tinyint NOT NULL DEFAULT '0' COMMENT '分析建议0可选，-1禁止用于分析维度，1建议',
  yn tinyint NOT NULL DEFAULT '1' COMMENT '是否有效',
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS sales_data (
    row_id INT PRIMARY KEY COMMENT '行 ID',
    order_id VARCHAR(50) DEFAULT NULL COMMENT '订单 ID',
    order_date DATE  COMMENT '订单日期',
    ship_date DATE COMMENT '发货日期',
    ship_mode VARCHAR(50) DEFAULT NULL COMMENT '邮寄方式',
    customer_id VARCHAR(50) DEFAULT NULL COMMENT '客户 ID',
    customer_name VARCHAR(100) DEFAULT NULL COMMENT '客户名称',
    segment VARCHAR(50) DEFAULT NULL COMMENT '细分',
    city VARCHAR(100) DEFAULT NULL COMMENT '城市',
    state_province VARCHAR(100) DEFAULT NULL COMMENT '省/自治区',
    country VARCHAR(100) DEFAULT NULL COMMENT '国家',
    region VARCHAR(50) DEFAULT NULL COMMENT '地区',
    product_id VARCHAR(50) DEFAULT NULL COMMENT '产品 ID',
    category VARCHAR(50) DEFAULT NULL COMMENT '产品类别',
    sub_category VARCHAR(50) DEFAULT NULL COMMENT '产品子类别',
    product_name VARCHAR(255) DEFAULT NULL COMMENT '产品名称',
    sales DECIMAL(10, 4) DEFAULT NULL COMMENT '销售额',
    quantity INT DEFAULT NULL COMMENT '销售数量',
    discount DECIMAL(10, 4) DEFAULT NULL COMMENT '折扣',
    profit DECIMAL(10, 4) DEFAULT NULL COMMENT '利润'
);

CREATE TABLE IF NOT EXISTS ai_agent_image_generation_record (
    id                 BIGINT       NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    request_id         VARCHAR(64)  NOT NULL COMMENT '单次生成请求ID',
    result_index       INT          NOT NULL DEFAULT 0 COMMENT '同批次结果图序号(0-based)',
    device_id          VARCHAR(128) NOT NULL COMMENT '匿名设备标识',
    user_id            BIGINT       NULL     COMMENT '认证用户ID(预留)',
    prompt             TEXT         NOT NULL COMMENT '生成提示词',
    mode               VARCHAR(16)  NOT NULL COMMENT '生成模式 images/edits',
    size               VARCHAR(32)  NULL     COMMENT '输出尺寸',
    batch_count        INT          NOT NULL DEFAULT 1 COMMENT '本批次生成图片总数',
    source_image_count INT          NOT NULL DEFAULT 0 COMMENT '参考图数量',
    mask_image_count   INT          NOT NULL DEFAULT 0 COMMENT '蒙版图数量',
    used_fallback      TINYINT(1)   NOT NULL DEFAULT 0 COMMENT '是否走兼容降级接口',
    file_name          VARCHAR(255) NULL     COMMENT '结果图片文件名',
    oss_url            VARCHAR(1024) NULL    COMMENT '文件下载地址或对象存储地址',
    domain_url         VARCHAR(1024) NULL    COMMENT '文件预览地址',
    download_url       VARCHAR(1024) NULL    COMMENT '稳定下载地址',
    file_size          BIGINT       NULL     COMMENT '文件大小(字节)',
    mime_type          VARCHAR(128) NULL     COMMENT '结果图片MIME类型',
    create_time        DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time        DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted            TINYINT(1)   NOT NULL DEFAULT 0 COMMENT '软删除',
    PRIMARY KEY (id),
    UNIQUE KEY uk_request_result (request_id, result_index),
    KEY idx_device_create (device_id, deleted, create_time DESC),
    KEY idx_user_create (user_id, deleted, create_time DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='生图工作台结果明细表';

CREATE TABLE IF NOT EXISTS ai_agent_dialogue_run (
    id                      BIGINT         NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    run_uid                 VARCHAR(64)    NOT NULL COMMENT '对外稳定运行ID，首期复用 requestId',
    request_id              VARCHAR(64)    NOT NULL COMMENT '单次请求ID',
    session_id              VARCHAR(64)    NOT NULL COMMENT '会话ID',
    entry_agent             VARCHAR(32)    NOT NULL COMMENT '入口执行链 react / plan_solve',
    status                  TINYINT        NOT NULL DEFAULT 0 COMMENT '0=RUNNING,1=SUCCESS,2=FAILED,3=TIMEOUT,4=STOPPED',
    query_text              MEDIUMTEXT     NULL COMMENT '用户原始问题',
    final_summary_text      MEDIUMTEXT     NULL COMMENT '最终总结文本',
    llm_call_count          INT            NOT NULL DEFAULT 0 COMMENT 'LLM 调用次数',
    tool_call_count         INT            NOT NULL DEFAULT 0 COMMENT '工具调用次数',
    artifact_count          INT            NOT NULL DEFAULT 0 COMMENT '产物数量',
    prompt_tokens_total     INT            NOT NULL DEFAULT 0 COMMENT 'LLM 输入 token 总量',
    completion_tokens_total INT            NOT NULL DEFAULT 0 COMMENT 'LLM 输出 token 总量',
    total_tokens_total      INT            NOT NULL DEFAULT 0 COMMENT 'LLM token 总量',
    error_code              VARCHAR(64)    NULL COMMENT '失败码',
    error_msg               TEXT           NULL COMMENT '失败信息',
    started_at              DATETIME(3)    NOT NULL COMMENT 'run 开始时间',
    finished_at             DATETIME(3)    NULL COMMENT 'run 结束时间',
    duration_ms             BIGINT         NULL COMMENT 'run 耗时毫秒',
    create_time             DATETIME       NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time             DATETIME       NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted                 TINYINT(1)     NOT NULL DEFAULT 0 COMMENT '软删除',
    PRIMARY KEY (id),
    UNIQUE KEY uk_dialogue_run_uid (run_uid),
    UNIQUE KEY uk_dialogue_request_id (request_id),
    KEY idx_dialogue_session_create (session_id, deleted, create_time DESC),
    KEY idx_dialogue_entry_status (entry_agent, status, deleted, create_time DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='对话执行总账表';

CREATE TABLE IF NOT EXISTS ai_agent_llm_invocation (
    id                BIGINT         NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    run_id            BIGINT         NOT NULL COMMENT '所属 run ID',
    invocation_seq    INT            NOT NULL COMMENT 'run 内递增序号',
    agent_name        VARCHAR(32)    NOT NULL COMMENT '当前 agent 名称',
    step_no           INT            NULL COMMENT '当前步号',
    call_kind         VARCHAR(16)    NOT NULL COMMENT 'ask / askTool',
    streaming         TINYINT(1)     NOT NULL DEFAULT 0 COMMENT '是否流式',
    model_name        VARCHAR(128)   NULL COMMENT '模型名',
    response_text     MEDIUMTEXT     NULL COMMENT '完整响应文本',
    tool_call_count   INT            NOT NULL DEFAULT 0 COMMENT '工具调用数量',
    prompt_tokens     INT            NOT NULL DEFAULT 0 COMMENT 'prompt token',
    completion_tokens INT            NOT NULL DEFAULT 0 COMMENT 'completion token',
    total_tokens      INT            NOT NULL DEFAULT 0 COMMENT 'total token',
    finish_reason     VARCHAR(32)    NULL COMMENT '完成原因',
    status            TINYINT        NOT NULL DEFAULT 0 COMMENT '0=RUNNING,1=SUCCESS,2=FAILED,3=TIMEOUT',
    error_msg         TEXT           NULL COMMENT '错误信息',
    started_at        DATETIME(3)    NOT NULL COMMENT '开始时间',
    finished_at       DATETIME(3)    NULL COMMENT '结束时间',
    duration_ms       BIGINT         NULL COMMENT '耗时毫秒',
    create_time       DATETIME       NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time       DATETIME       NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted           TINYINT(1)     NOT NULL DEFAULT 0 COMMENT '软删除',
    PRIMARY KEY (id),
    UNIQUE KEY uk_run_invocation_seq (run_id, invocation_seq),
    KEY idx_llm_run_seq (run_id, deleted, invocation_seq),
    KEY idx_llm_model_create (model_name, deleted, create_time DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='LLM 调用账本表';

CREATE TABLE IF NOT EXISTS ai_agent_tool_invocation (
    id                BIGINT         NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    run_id            BIGINT         NOT NULL COMMENT '所属 run ID',
    llm_invocation_id BIGINT         NOT NULL COMMENT '来源 LLM invocation ID',
    tool_call_id      VARCHAR(128)   NOT NULL COMMENT '模型返回的 toolCallId',
    dispatch_index    INT            NOT NULL COMMENT '模型原始分发顺序',
    agent_name        VARCHAR(32)    NOT NULL COMMENT '当前 agent 名称',
    step_no           INT            NULL COMMENT '当前步号',
    tool_name         VARCHAR(128)   NOT NULL COMMENT '工具名称',
    tool_provider     VARCHAR(64)    NULL COMMENT '工具提供方 local / mcp',
    input_json        JSON           NOT NULL COMMENT '工具入参 JSON',
    llm_oberserve     MEDIUMTEXT     NULL COMMENT '回传给主智能体的最终 observation',
    output_json       JSON           NULL COMMENT '工具结构化输出',
    status            TINYINT        NOT NULL DEFAULT 0 COMMENT '0=RUNNING,1=SUCCESS,2=FAILED,3=TIMEOUT',
    error_msg         TEXT           NULL COMMENT '错误信息',
    started_at        DATETIME(3)    NOT NULL COMMENT '开始时间',
    finished_at       DATETIME(3)    NULL COMMENT '结束时间',
    duration_ms       BIGINT         NULL COMMENT '耗时毫秒',
    create_time       DATETIME       NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time       DATETIME       NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted           TINYINT(1)     NOT NULL DEFAULT 0 COMMENT '软删除',
    PRIMARY KEY (id),
    UNIQUE KEY uk_run_tool_call (run_id, tool_call_id),
    UNIQUE KEY uk_llm_dispatch (llm_invocation_id, dispatch_index),
    KEY idx_tool_run_create (run_id, deleted, create_time DESC),
    KEY idx_tool_name_create (tool_name, deleted, create_time DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='工具调用账本表';

CREATE TABLE IF NOT EXISTS ai_agent_artifact (
    id                 BIGINT         NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    run_id             BIGINT         NOT NULL COMMENT '所属 run ID',
    tool_invocation_id BIGINT         NULL COMMENT '所属 tool invocation，输入文件为空',
    tool_call_id       VARCHAR(128)   NULL COMMENT '所属 toolCallId，输入文件为空',
    artifact_role      VARCHAR(16)    NOT NULL COMMENT 'input / output',
    visibility         VARCHAR(16)    NOT NULL COMMENT 'visible / internal',
    source_type        VARCHAR(32)    NOT NULL COMMENT 'user_upload / tool_output',
    source_name        VARCHAR(128)   NULL COMMENT '来源名称',
    file_name          VARCHAR(256)   NOT NULL COMMENT '文件名',
    storage_key        VARCHAR(512)   NOT NULL DEFAULT '' COMMENT '稳定资源 key',
    download_url       VARCHAR(1024)  NULL COMMENT '下载地址',
    preview_url        VARCHAR(1024)  NULL COMMENT '预览地址',
    mime_type          VARCHAR(128)   NULL COMMENT 'MIME 类型',
    file_size          BIGINT         NULL COMMENT '文件大小',
    file_hash          VARCHAR(128)   NULL COMMENT '文件哈希',
    metadata_json      JSON           NULL COMMENT '扩展元数据',
    create_time        DATETIME       NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time        DATETIME       NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted            TINYINT(1)     NOT NULL DEFAULT 0 COMMENT '软删除',
    PRIMARY KEY (id),
    UNIQUE KEY uk_run_tool_storage (run_id, tool_call_id, storage_key),
    KEY idx_artifact_run_create (run_id, deleted, create_time DESC),
    KEY idx_artifact_tool (tool_invocation_id, deleted, create_time DESC),
    KEY idx_artifact_role (artifact_role, visibility, deleted, create_time DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='执行输入输出产物账本表';
